plugins {
    id 'com.android.application'
}

android {
    namespace 'ai.deepseek.harness.client'
    compileSdk 36
    buildToolsVersion '35.0.0'

    defaultConfig {
        applicationId 'ai.deepseek.harness.client'
        minSdk 26
        targetSdk 36
        versionCode 17
        versionName '1.1.2'
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
